
DROP DATABASE IF EXISTS `sc-dev`;
CREATE DATABASE IF NOT EXISTS `sc-dev`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `sc-dev`.`USER` ;
CREATE TABLE `sc-dev`.`USER`  (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ACCOUNT` varchar(50) NOT NULL UNIQUE,
  `USER_PASSWORD` varchar(50) NOT NULL,
  `USER_TYPE` int NOT NULL default 0,
  `USER_NAME` varchar(50) NOT NULL DEFAULT 'user',
  `USER_DEPARTMENT_ID` int NULL DEFAULT NULL,
  `USER_EMAIL` varchar(50)  NULL DEFAULT NULL,
  `USER_START_TIME` TIME NULL DEFAULT NULL,
  `USER_END_TIME` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `sc-dev`.`DEPARTMENT`;
CREATE TABLE `sc-dev`.`DEPARTMENT`  (
  `DEPARTMENT_ID` int NOT NULL AUTO_INCREMENT,
  `DEPARTMENT_NAME` varchar(50) NOT NULL,
  `DEPARTMENT_INTRO`varchar(200) NOT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

DROP TABLE IF EXISTS `sc-dev`.`FILE_SYSTEM`;
CREATE TABLE `sc-dev`.`FILE_SYSTEM`  (
  `FILE_ID` int NOT NULL AUTO_INCREMENT,
  `FILE_SIZE`  varchar(50) NOT NULL,
  `FILE_NAME` varchar(50) NOT NULL,
  `FILE_URL` varchar(50) NOT NULL,
  `FILE_TYPE` varchar(50) NOT NULL,
  `UP_LOADER_NAME` varchar(50) NOT NULL,
  `FILE_INFO` varchar(200) NOT NULL,
  PRIMARY KEY (`FILE_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;